//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    
    public partial class SP_NGUOI_DUNG_QUYEN_GetBy_ID_NGUOIDUNG_Result1
    {
        public int ID { get; set; }
        public Nullable<int> ID_NGUOIDUNG { get; set; }
        public Nullable<int> ID_QUYEN { get; set; }
        public string HO_TEN_NGUOI_DUNGJoin { get; set; }
        public Nullable<int> ID_DONVI_NGUOI_DUNGJoin { get; set; }
        public string TEN_QUYEN_QUYENJoin { get; set; }
        public int ID_QUYENJoin { get; set; }
    }
}
